name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUXT_PUBLIC_SITE_NAME: ${{ vars.NUXT_PUBLIC_SITE_NAME }}
      NUXT_PUBLIC_SITE_DESCRIPTION: ${{ vars.NUXT_PUBLIC_SITE_DESCRIPTION }}
      NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
      NUXT_PUBLIC_BASE: /dac_tohoku/
      NUXT_API_EVENT_DATA: ${{ vars.NUXT_API_EVENT_DATA }}
      NUXT_API_NEW_INFO: ${{ vars.NUXT_API_NEW_INFO }}
      NUXT_API_SESSION_LIST: ${{ vars.NUXT_API_SESSION_LIST }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'yarn' }
      - run: yarn install --frozen-lockfile
      - run: echo "NUXT_PUBLIC_BASE=/dac_tohoku/" >> $GITHUB_ENV

      # （任意）WIP中は noindex にしたい場合:
      - run: echo "NUXT_PUBLIC_INDEXABLE=false" >> $GITHUB_ENV

      - run: npx nuxi generate
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./dist }

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
